# Generated by Django 5.1.6 on 2025-02-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='daily_insulin_level',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dietary_preferences',
            field=models.CharField(choices=[('vegetarian', 'Vegetarian'), ('non-vegetarian', 'Non-Vegetarian'), ('vegan', 'Vegan')], default='vegetarian', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='family_history',
            field=models.CharField(choices=[('diabetic', 'Diabetic'), ('non-diabetic', 'Non-Diabetic')], default='non-diabetic', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='health_condition_preferences',
            field=models.CharField(choices=[('diabetes', 'Diabetes'), ('cardiovascular', 'Cardiovascular'), ('both', 'Both')], default='diabetes', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='physical_activity',
            field=models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], default='low', max_length=20),
        ),
    ]
