# Generated by Django 5.1.6 on 2025-03-18 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_alter_userprofile_age_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='daily_insulin_level',
            new_name='insulin',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='dietary_preferences',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='family_history',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='health_condition_preferences',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='physical_activity',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='goal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
