# Generated by Django 5.1.6 on 2025-03-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_alter_userprofile_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='has_diabetes',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='health_condition_preferences',
            field=models.CharField(blank=True, choices=[('diabetes', 'Diabetes'), ('cardiovascular', 'Cardiovascular'), ('both', 'Both'), ('none', 'None')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dietary_preference',
            field=models.CharField(blank=True, choices=[('vegetarian', 'Vegetarian'), ('non vegetarian', 'Non Vegetarian'), ('vegan', 'Vegan')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='family_history',
            field=models.TextField(blank=True, choices=[('diabetic', 'Diabetic'), ('non_diabetic', 'Non Diabetic')], null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='physical_activity',
            field=models.CharField(choices=[('sedentary', 'Sedentary (Minimal movement, mostly sitting)'), ('low_active', 'Low active (Light physical activity, occasional exercise)'), ('active', 'Active (Regular exercise, moderate physical activity)'), ('very_active', 'Very active (Intense daily physical activity or workouts)')], default='low_active', max_length=150),
        ),
    ]
