# Generated by Django 5.1.6 on 2025-03-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_remove_userprofile_has_diabetes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='dietary_preference',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dietary_preferences',
            field=models.CharField(blank=True, choices=[('vegetarian', 'Vegetarian'), ('non vegetarian', 'Non Vegetarian'), ('vegan', 'Vegan')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_diabetes',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='family_history',
            field=models.CharField(blank=True, choices=[('diabetic', 'Diabetic'), ('non_diabetic', 'Non Diabetic')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='health_condition_preferences',
            field=models.CharField(blank=True, choices=[('diabetes', 'Diabetes'), ('cardiovascular', 'Cardiovascular')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='physical_activity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10),
        ),
    ]
