/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/auth/editprofile`; params?: Router.UnknownInputParams; } | { pathname: `/auth/goalscreen`; params?: Router.UnknownInputParams; } | { pathname: `/auth/instructions`; params?: Router.UnknownInputParams; } | { pathname: `/auth/loginscreen`; params?: Router.UnknownInputParams; } | { pathname: `/auth/mealdetails`; params?: Router.UnknownInputParams; } | { pathname: `/auth/mealrecomdation`; params?: Router.UnknownInputParams; } | { pathname: `/auth/profilesetup`; params?: Router.UnknownInputParams; } | { pathname: `/auth/signupscreen`; params?: Router.UnknownInputParams; } | { pathname: `/auth/welcomescreen`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/home`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/log`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/profile`; params?: Router.UnknownInputParams; } | { pathname: `/search/[query]`, params: Router.UnknownInputParams & { query: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/editprofile`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/goalscreen`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/instructions`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/loginscreen`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/mealdetails`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/mealrecomdation`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/profilesetup`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/signupscreen`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/welcomescreen`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs/home`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs/log`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/search/[query]`, params: Router.UnknownOutputParams & { query: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/auth/editprofile${`?${string}` | `#${string}` | ''}` | `/auth/goalscreen${`?${string}` | `#${string}` | ''}` | `/auth/instructions${`?${string}` | `#${string}` | ''}` | `/auth/loginscreen${`?${string}` | `#${string}` | ''}` | `/auth/mealdetails${`?${string}` | `#${string}` | ''}` | `/auth/mealrecomdation${`?${string}` | `#${string}` | ''}` | `/auth/profilesetup${`?${string}` | `#${string}` | ''}` | `/auth/signupscreen${`?${string}` | `#${string}` | ''}` | `/auth/welcomescreen${`?${string}` | `#${string}` | ''}` | `/tabs/home${`?${string}` | `#${string}` | ''}` | `/tabs/log${`?${string}` | `#${string}` | ''}` | `/tabs/profile${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/auth/editprofile`; params?: Router.UnknownInputParams; } | { pathname: `/auth/goalscreen`; params?: Router.UnknownInputParams; } | { pathname: `/auth/instructions`; params?: Router.UnknownInputParams; } | { pathname: `/auth/loginscreen`; params?: Router.UnknownInputParams; } | { pathname: `/auth/mealdetails`; params?: Router.UnknownInputParams; } | { pathname: `/auth/mealrecomdation`; params?: Router.UnknownInputParams; } | { pathname: `/auth/profilesetup`; params?: Router.UnknownInputParams; } | { pathname: `/auth/signupscreen`; params?: Router.UnknownInputParams; } | { pathname: `/auth/welcomescreen`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/home`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/log`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/profile`; params?: Router.UnknownInputParams; } | `/search/${Router.SingleRoutePart<T>}` | { pathname: `/search/[query]`, params: Router.UnknownInputParams & { query: string | number; } };
    }
  }
}
